### ISSUE TITLE
ubifs should scan for the most recent master

### ISSUE THREAD

**Issue by retryfail** [jrspruitt/ubi_reader#38]
An LEB may contain multiple copies of the master node and a scan should be performed to find the latest master; ubi_reader is only looking at the first master in the LEB which causes corrupt extraction if it isn't the latest.

ref: https://github.com/torvalds/linux/blob/master/fs/ubifs/master.c#L82

**Comment by retryfail** [comment]
a quick and dirty implementation -
https://github.com/retryfail/ubi_reader/commit/7bbca3133ad6cee2b24763009ca437123e5507c5

**Comment by jrspruitt** [comment]
I totally forgot about this, thanks for pointing it out. When I get some time I'll add it.

**Comment by jrspruitt** [comment]
Hi retryfail,

I changed the behavior to pick the valid Master Node if they were not both valid instead of causing a fatal error. Looking over the UBIFS source this is the best I could tell they were doing, it seemed if they were not both equal, it required some sort of clean up of the nodes, which is beyond the scope of ubi_reader. Hopefully this works, as I don't have a test case image to work against.

-Jason
