### ISSUE TITLE
Need Help For Build Ubifs

### ISSUE THREAD

**Issue by kingvuplus** [jrspruitt/ubi_reader#8]
Hello

the extract Ubifs is good for me  but i want to Build My Image again but i can't 
any idea

**Comment by jrspruitt** [comment]
Hi It's been a while since I made an image, but these two sites are usually what I reference
http://free-electrons.com/blog/creating-flashing-ubi-ubifs-images/
http://elinux.org/UBIFS#Creating_UBI_Image

ubi_reader has a script to get the relevant information and creates a shell script to use to generate the image. You'll need mtd-utils installed. Run ubireader_utils_info /path/to/ubi|ubifs file it'll create a directory with the script and config file, it will also print out all the settings if you need something different than the script creates.
